FROM node:22.17.0 as builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

ARG MODE=docker

RUN yarn build

FROM nginx:alpine as runner

COPY --from=builder app/dist/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf