// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: libs/shared/src/infrastructure/interfaces/grpc/product/products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PRODUCTS_GRPC_PACKAGE";

export interface GetProductByIdRequest {
  id: string;
}

export interface Product {
  id: string;
  title: string;
  color: string;
  description: string;
  price: number;
  currency: string;
  stock: number;
  soldQuantity: number;
  imagesIds: string[];
  mainImageId: string;
  categories: string[];
  rating: number;
  reviewsCount: number;
  isBestSeller: boolean;
  freeReturnDays: number;
  factoryWarrantyMonths: number;
  attributes: ProductAttributeNormalized[];
  sellerId: string;
  paymentMethods: string[];
  discountPercentage?: number | undefined;
}

export interface ProductAttributeNormalized {
  name: string;
  value: string;
  category: string;
  highlighted?: boolean | undefined;
}

export const PRODUCTS_GRPC_PACKAGE_PACKAGE_NAME = "PRODUCTS_GRPC_PACKAGE";

export interface ProductServicesClient {
  getProductById(request: GetProductByIdRequest): Observable<Product>;
}

export interface ProductServicesController {
  getProductById(request: GetProductByIdRequest): Observable<Product>;
}

export function ProductServicesControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProductById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductServices", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductServices", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICES_SERVICE_NAME = "ProductServices";
