// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: apps/reviews/src/reviews.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "REVIEWS_GRPC_PACKAGE";

export interface GetReviewsByProductIdRequest {
  productId: string;
}

export interface Review {
  id: string;
  productId: string;
}

export const REVIEWS_GRPC_PACKAGE_PACKAGE_NAME = "REVIEWS_GRPC_PACKAGE";

export interface ReviewServicesClient {
  getReviewsByProductId(request: GetReviewsByProductIdRequest): Observable<Review>;
}

export interface ReviewServicesController {
  getReviewsByProductId(request: GetReviewsByProductIdRequest): Observable<Review>;
}

export function ReviewServicesControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getReviewsByProductId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ReviewServices", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ReviewServices", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const REVIEW_SERVICES_SERVICE_NAME = "ReviewServices";
