FROM node:22.17.0 AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build shared

RUN yarn build gateway

FROM node:22.17.0-alpine as runner

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --prod --frozen-lockfile && yarn cache clean

COPY public ./public

COPY --from=builder app/dist/ ./dist/

CMD sh -c "node dist/apps/gateway/main"